### ISSUE TITLE
textinput currently renders long text strings outside its bounds

### ISSUE THREAD

**Issue by pneuma163** [focustense/StardewUI#66]
Suggestion: limit rendering of text in a textinput to the bounds of the text box regardless of the length of the text.

Possible enhancements:
A: allow horizontal scrolling on the textinput if the input string is too long to fit
B: prevent additional text from being added via key presses or copy and paste if it would be longer than the text box
C: both A and B as options for the mod maker

**Comment by focustense** [comment]
You can (and generally should) limit the input length with the [MaxLength property](https://focustense.github.io/StardewUI/reference/stardewui/widgets/textinput/#maxlength).

The expected/previous behavior if the text is too long, at this point, is to render it with an ellipsis. If it is rendering outside the bounds, a regression may have crept in. I'll investigate.

**Comment by focustense** [comment]
This is no repro for me, unless you count the truncating ellipsis rendering ever so slightly outside of the box. Could have been solved by #73 but I don't think so, AFAIK the behavior hasn't changed.

I'll still see if I can do some kind of horizontal scrolling, though not sure how easy it is.
