### ISSUE TITLE
v0.4.1 Pre-Release Flagged by Google Chrome/Windows Defender as "Virus Detected".

### ISSUE THREAD

**Issue by Sierra0001** [focustense/StardewUI#74]
As per title, the current pre-release of v0.4.1 is flagged when users attempt to download the mod.

**Comment by focustense** [comment]
I submitted to MS's analysis site as false positive so we'll see how it goes.

**Comment by focustense** [comment]
Given that 0.4.2 is now out to replace the 0.4.1 prerelease, is this still an issue? (i.e. is 0.4.2 getting flagged as well?)

I haven't heard any reports, but the typical Nexus downloader might not know what to do or how to report it.

**Comment by focustense** [comment]
From what I can tell, the latest version (0.4.2) has something like 4-5k downloads and no one's complained yet, so I think this is probably moot. Either the false positive reports resolved the issue, or the issue just didn't happen again with 0.4.2.

Thanks again for the original report!
